### ISSUE TITLE
Social Media/Message field for contacts unable to be edited

### ISSUE THREAD

**Issue by cairocoder01** [DiscipleTools/disciple-tools-mobile-app#38]
MexSurfer:
> Change the Facebook icon for message (on the details tab for a contact) to be a more generic speech bubble icon.

Upon testing, what is labelled as "Messages" in the app should be for the field called "Social Media" in the web app. In the app, it shows a Facebook icon, which is inaccurate. However, it does not seem to load the data from the web app and is unable to be edited in the edit view.

**Comment by mikeallbutt** [comment]
Also, it is not available in the edit mode at present.

**Comment by cairocoder01** [comment]
### Screenshot 1 ###
![image](https://user-images.githubusercontent.com/44169599/67476218-e0771900-f657-11e9-9153-61095095806e.png)
### Screenshot 2 ###
![image](https://user-images.githubusercontent.com/44169599/67476271-fab0f700-f657-11e9-962a-53fcc8319ae3.png)
### Screenshot 3 ###
![image](https://user-images.githubusercontent.com/44169599/67478356-2df58500-f65c-11e9-84c0-e63778dd372d.png)


## Requirements ##
* Social Media data should be displayed on the contact view/detail screen
  * Icon from Ionicons: `chatboxes`
  * Show both username and network (as styled in screenshot 3 above)
  * Ensure there is more vertical spacing between each pair of username/network than between the username and its associated social network name (see screenshot 3 above)
* Include Social Media field on contact edit screen (reference screenshot 1 for example from Android contacts app)
  * Icon from Ionicons: `chatboxes`
  * Field should consist of two inputs: 
    * Dropdown selection for social media platform (see screenshot 2 above for options, but should be pulled from site settings API since it can be changed for each instance of DT)
    * Text input for contact's username or url on the given platform
    * Delete icon should be to the right of the text input
  * Field inputs will be stacked vertically
    * Between groups of the two inputs, there should be an extra 10-20px vertical margin/spacing in order to visually group the dropdown and text inputs

**Comment by raschdiaz** [comment]
Hi, what its the end-point that return the list of social media plaforms?

**Comment by cairocoder01** [comment]
@corsacca Can you confirm: would the list of social media options come from the `/contacts/settings` endpoint in the `channels` property? We would just need to exclude `phone`, `email`, and `address`, correct?

**Comment by corsacca** [comment]
@cairocoder01 Yes.
To correspond to the field name you'll need to add `contact_` before the channel name.

**Comment by raschdiaz** [comment]
Hi @cairocoder01 @mikeallbutt @corsacca, i have finished to implement this issue. Can you test it and confirm i all works right please?

**Comment by cairocoder01** [comment]
I'm unable to see this change when using https://expo.io/@hans.rasch/discipletoolsapp. @raschdiaz Can you confirm that it is published to that Expo account?

**Comment by corsacca** [comment]
I think we switched to https://expo.io/@discipletools/discipletoolsapp

**Comment by cairocoder01** [comment]
Thanks @raschdiaz . A few updates:

* [ ] (see screenshot 1) As shown in the design above, please align the icon at the top.
* [ ] If there is not a username for a given messaging channel, it should not show anything. Currently it shows the name of the network.
* [ ] (screenshot 2) On edit screen, remove the auto-capitalization of the first letter in the text input
* [ ] (screenshot 2) On edit screen, after adding two items, the new fields get added before the last item instead of being added at the top. New items should always be added to the top of the list
* [ ] (screenshot 2) On edit screen, move minus/remove icon to be inline with the text input, not centered between it and the dropdown
* [ ] (screenshot 2) On edit screen, we need a little more space below each dropdown so that it is more visually separated from the next item in the list.
* [ ] On edit screen, can we update the style of the text input to be a single underline (instead of full border) to match the Full Name field at the top of the view?
* [ ] On edit screen, can we add a bottom border on the dropdown to look similar to the Full Name field?

### Screenshot 1 ###
![Screenshot_20191104-125958](https://user-images.githubusercontent.com/44169599/68116701-28255c80-ff04-11e9-8bb1-90514f88fcb0.png)

### Screenshot 2 ###
![Screenshot_20191104-130309](https://user-images.githubusercontent.com/44169599/68116702-28255c80-ff04-11e9-9073-e5beb689795c.png)

**Comment by mikeallbutt** [comment]
Here is the link to the video about the showing the bug that adds multiple fields.
https://drive.google.com/file/d/1vVUNg1sngDafFf60sZGlmLsf7oXThzqu/view?usp=sharing

**Comment by raschdiaz** [comment]
Hi @cairocoder01 @mikeallbutt i have done the updates that you request. But we found some issues with this point:

"On edit screen, can we add a bottom border on the dropdown to look similar to the Full Name field?"

That seems the Picker component of NativeBase does not able be stylized to add borders, see this issue to more info: [https://github.com/GeekyAnts/NativeBase/issues/122](url)

**Comment by cairocoder01** [comment]
Thanks for the update @raschdiaz. Almost everything looks to be working.

One outstanding issue and one new issue:
* [ ] When adding more than two items to the list, it does not add them at the top of the list.
* [ ] When editing a contact, the picker/dropdown does not seem to show the correct social network but always shows "Facebook" (see screenshots below)

![Screenshot_20191110-121255](https://user-images.githubusercontent.com/44169599/68542295-f6087480-03b3-11ea-9cdb-dba8f8bf3a52.png)
![Screenshot_20191110-121304](https://user-images.githubusercontent.com/44169599/68542297-f9036500-03b3-11ea-9dfa-4673a29073b5.png)

**Comment by raschdiaz** [comment]
Hi @cairocoder01 . I realized a commit push with the fix that you mentioned in the 2nd point. 

About the first point, the new fields are added in the top of the list **but** this fields are sorted by the contactSettings list fields. Now, this order its done this way because the socialMedia values are separated in multiple collections by the "social media name" (contact_facebook, contact_twitter...etc). If all the field were listed in only one property (like contact_social_media), we can put the new fields at the top of the list no matter the "social media type".

**Comment by cairocoder01** [comment]
The second item seems to be fixed.

So the problem is that you don't have one consolidated list of all of the social media accounts. You could fix that by merging the data into a single list in your state for easier management in the UI, and then you can transform it back when you need to save it.

For example, if you get this from the API...

```
"contact_facebook": [
    {
        "verified": false,
        "value": "myusername",
        "key": "contact_facebook_31a"
    },
    {
        "verified": false,
        "value": "second-username",
        "key": "contact_facebook_b38"
    }
],
"contact_twitter": [
    {
        "verified": false,
        "value": "third-username",
        "key": "contact_twitter_e0e"
    },
    {
        "verified": false,
        "value": "tweetme",
        "key": "contact_twitter_d6c"
    }
],
```

You could transform this into a local state of...

```
"socialMediaAccounts": [
    {
        "verified": false,
        "value": "myusername",
        "key": "contact_facebook_31a",
        "channel": "contact_facebook"
    },
    {
        "verified": false,
        "value": "second-username",
        "key": "contact_facebook_b38",
        "channel": "contact_facebook"
    },
    {
        "verified": false,
        "value": "third-username",
        "key": "contact_twitter_e0e",
        "channel": "contact_twitter"
    },
    {
        "verified": false,
        "value": "tweetme",
        "key": "contact_twitter_d6c",
        "channel": "contact_twitter"
    }
],
```

Now you have a single list that more closely matches how we are displaying it in the UI. That should hopefully make it easier.

**Comment by jl0325** [comment]
@cairocoder01, Yes! A single list make it easier. I'm working to update this changes

**Comment by jl0325** [comment]
The icon position was fixed!

![WhatsApp Image 2019-11-14 at 10 31 42 AM](https://user-images.githubusercontent.com/10079527/68871175-09745200-06ca-11ea-9b63-9758428640a6.jpeg)

**Comment by zdmc23** [comment]
Hi @jl0325 , would you please issue a Pull Request for this fix, and we'll get it merged and confirmed? Thx!

**Comment by raschdiaz** [comment]
Hi @zdmc23 we have created a new pull-request merged with you development branch: https://github.com/DiscipleTools/disciple-tools-mobile-app/pull/107

**Comment by cairocoder01** [comment]
@raschdiaz The issue about not adding new items at the top of the list is still not working. When I add a new value, instead of being added to the top of the list, it is added after the previous new items. I think it might be because I did not change the value in the dropdown, so maybe it's not properly assigned to a given network (default: Facebook).

There's also an old issue that has been added back in after being fixed previously: social network names that don't have a corresponding value are showing on the contact detail screen. We should only show social networks if there is a username/value saved for them.

![1096731703](https://user-images.githubusercontent.com/44169599/69048455-24b2ca80-0a06-11ea-935f-bf00a3f6ab6e.png)

![Screenshot_20191118-131254](https://user-images.githubusercontent.com/44169599/69048464-28465180-0a06-11ea-8a8c-6ade0f4fbebb.png)

**Comment by jl0325** [comment]
Remove social media label when the user don't have information. Fixed order of new social media field. 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/10079527/69818103-13b64600-11ca-11ea-8bdb-0332291469eb.gif)

**Comment by zdmc23** [comment]
I thought that it was working, but when I added a new SM entry, and left it blank/empty and clicked `Save`, then it is being displayed, and between 2 other entries with proper values

![C11B9271-2EF9-425A-ABDC-3D2B08C669CD](https://user-images.githubusercontent.com/191707/69888456-f1035a80-12b9-11ea-83d5-acd6af82a806.png)

**Comment by zdmc23** [comment]
This issue is still open bc it continues to save empty entries (see screenshot)

Steps to reproduce:
1. Edit Contact
1. Add 2 Social Media (click ‘+’ 2 times)
1. Leave first entry empty/blank
1. Enter value in 2nd entry
1. Save

![CE8A819B-C0C4-4A7E-9EB1-5E475FD867CA](https://user-images.githubusercontent.com/191707/72682909-5f85bd00-3aa0-11ea-8472-75638c102a60.png)

**Comment by zdmc23** [comment]
The blank/empty entry no longer displays, but there remains an issue where previously blank/empty values are present when in Edit Mode (likely stored in Async/Persistent Storage), and when you attempt to delete it manually the app will crash

Steps to reproduce:
1. Select `Zac Contact` Contact
1. Click `Edit`
1. Manually remove empty/blank Facebook entry (click ‘-‘ button)

![47E99823-5BB5-47FB-96E1-7084DCFE3452](https://user-images.githubusercontent.com/191707/72897077-0eb7d380-3cef-11ea-8c02-8b4403e3e1f5.png)
![E9F0DA77-4838-4723-8608-74C16B831C86](https://user-images.githubusercontent.com/191707/72897078-0eb7d380-3cef-11ea-818d-7e1205f5c008.png)
